### ISSUE TITLE
[2DS] 9.2 -> 2.1 one click setup fucked up

### ISSUE THREAD

**Issue by Amadren** [d0k3/OTPHelper#16] opened 2016-05-30 17:24 UTC
Read the full story here: https://github.com/Plailect/Guide/issues/164

OTPHelper verified the emunand, flashed it to sysnand and.... my sysnand was bricked.

**Comment by d0k3** [comment] 2016-05-30 21:16
I have to slightly disagree with the wording of this issue. One Click Setups safety detection routines can catch most issues, but not all (I'd say 99% of issues are catched, among them everything a user can possibly do wrong), the remainder is uncertain and may be a result of our software doing what Nintendo does not want. The actual issue is most likely not in OTPHelper, but somewhere else, and may be even beyound devs reach.

Anyways, get that hardmod, join us on #Cakey. I want to have a look at that NANDs contents. Also, don't just use the hardmod to restore, first dump the broken NAND. Maybe OTPHelper will be able to catch this in the future.

**Comment by d0k3** [comment] 2016-06-14 11:31
Closing that issue here. @Amadren - this was not caused by OTPHelper but rather by something earlier, something that OTPHelper could not detect. Join us on freenode #Cakey if you want to help find the cause behind the brick.

**Closed by d0k3** 2016-06-14 11:31 UTC
